name: pre-commit

on:
  pull_request:
  push:
    branches: [master]

jobs:
  pre-commit-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: install dev dependencies
      run: pip3 install -U -r requirements-dev.txt
    - uses: pre-commit/action@v2.0.3
